package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func testDoc(t *testing.T) doc {
	t.Helper()
	return doc{
		Fonts: map[string]string{"sans": "Inter", "mono": "JetBrains Mono"},
		Colors: map[string]pair{
			"bg":                 {Light: "#fbf9f2", Dark: "#1A1A1A"},
			"on-surface-variant": {Light: "#45474c", Dark: "#AFAFAF"},
			"sidebar-active-bg":  {Light: "#eae8e1", Dark: "rgba(230,126,81,0.1)"},
			"nav-border":         {Light: "transparent", Dark: "rgba(255,255,255,0.05)"},
			"kpi-1-bg":           {Light: "#f6f4ec", Dark: "#1F1F1F"},
		},
		Effects: map[string]pair{
			"img-filter": {Light: "grayscale(1)", Dark: "grayscale(1)"},
		},
	}
}

// The browser gets the palette as written. Compositing rgba() against the
// background is what the page already does correctly, and a pre-flattened
// value would drop the translucency the design depends on.
func TestRenderCSS(t *testing.T) {
	css, err := renderCSS(testDoc(t))
	if err != nil {
		t.Fatalf("renderCSS: %v", err)
	}
	for _, want := range []string{
		":root {",
		".dark {",
		"@theme inline {",
		"--sidebar-active-bg: rgba(230,126,81,0.1);", // kept translucent, not flattened
		"--nav-border: transparent;",
		"--img-filter: grayscale(1);", // effects are web-only but still web
		"--color-on-surface-variant: var(--on-surface-variant);",
		"--font-sans: Inter",
	} {
		if !strings.Contains(css, want) {
			t.Errorf("generated CSS is missing %q", want)
		}
	}
}

// The terminal gets solid colours only. lipgloss takes one colour per cell, so
// a token that reaches it still saying rgba() is a token that will not render.
func TestRenderGo(t *testing.T) {
	src, err := renderGo(testDoc(t))
	if err != nil {
		t.Fatalf("renderGo: %v", err)
	}
	for _, want := range []string{
		"// Code generated by gentokens. DO NOT EDIT.",
		"package theme",
		"OnSurfaceVariant string",
		"Kpi1Bg string",
		`Bg:               "#fbf9f2"`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("generated Go is missing %q", want)
		}
	}
	for _, unwanted := range []string{"rgba(", "transparent", "ImgFilter"} {
		if strings.Contains(src, unwanted) {
			t.Errorf("generated Go still carries %q — the terminal cannot use it", unwanted)
		}
	}
	// 0.1 of #e67e51 over #1a1a1a, resolved by the same arithmetic the colour
	// test pins down.
	if !strings.Contains(src, `SidebarActiveBg: "#2e2420"`) {
		t.Error("generated Go did not flatten sidebar-active-bg against the dark background")
	}
}

// The committed outputs have to match the source they claim to come from.
// Without this, editing tokens.json and forgetting to regenerate leaves two
// palettes that disagree — exactly the split the single source exists to
// prevent.
func TestGeneratedFilesAreCurrent(t *testing.T) {
	root := filepath.Join("..", "..", "..")
	d, err := load(filepath.Join(root, "design", "tokens.json"))
	if err != nil {
		t.Fatalf("load tokens: %v", err)
	}

	for _, c := range []struct {
		path   string
		render func(doc) (string, error)
	}{
		{filepath.Join(root, "internal", "theme", "tokens.go"), renderGo},
		{filepath.Join(root, "frontend", "src", "tokens.css"), renderCSS},
	} {
		want, err := c.render(d)
		if err != nil {
			t.Fatalf("render %s: %v", c.path, err)
		}
		got, err := os.ReadFile(c.path)
		if err != nil {
			t.Fatalf("read %s: %v", c.path, err)
		}
		if string(got) != want {
			t.Errorf("%s is stale — run `go generate ./...`", c.path)
		}
	}
}
