// Command gentokens turns design/tokens.json into the two forms the palette is
// consumed in: CSS custom properties for the web dashboard and Go constants for
// the TUI.
//
// It exists so the two surfaces cannot drift. A colour edited in one and not
// the other is the same class of defect as a rule that lives in two places, and
// this is the version of it that would go unnoticed longest — nothing breaks,
// the terminal is simply a slightly different shade than the browser.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"maps"
	"os"
	"slices"
	"strings"
	"unicode"

	"github.com/daniil/kb-engine/internal/theme"
)

// pair is one role's value in each theme.
type pair struct {
	Light string `json:"light"`
	Dark  string `json:"dark"`
}

// doc is design/tokens.json.
//
// Colors and Effects are separate because only one of them can reach a
// terminal: a grayscale filter or a blend mode has no meaning in a cell.
type doc struct {
	Fonts   map[string]string `json:"fonts"`
	Colors  map[string]pair   `json:"colors"`
	Effects map[string]pair   `json:"effects"`
}

// bgRole is the role every translucent colour is composited against — the same
// thing that sits behind them on the page.
const bgRole = "bg"

func load(path string) (doc, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return doc{}, fmt.Errorf("read tokens: %w", err)
	}
	var d doc
	if err := json.Unmarshal(raw, &d); err != nil {
		return doc{}, fmt.Errorf("parse %s: %w", path, err)
	}
	if _, ok := d.Colors[bgRole]; !ok {
		return doc{}, fmt.Errorf("%s: no %q role to composite against", path, bgRole)
	}
	return d, nil
}

// roles returns every role name in a stable order, so regenerating an unchanged
// source produces an unchanged file and a diff of the output stays meaningful.
func roles(m map[string]pair) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	slices.Sort(out)
	return out
}

// fontStack gives each font the fallbacks it needs before its own file has
// loaded. The roles are fixed by the design system, so an unknown one is a
// mistake worth failing on rather than a generic stack nobody chose.
func fontStack(role, family string) (string, error) {
	fallback, ok := map[string]string{
		"sans":    "ui-sans-serif, system-ui, sans-serif",
		"display": "ui-serif, Georgia, serif",
		"label":   "ui-sans-serif, system-ui, sans-serif",
		"mono":    "ui-monospace, SFMono-Regular, monospace",
	}[role]
	if !ok {
		return "", fmt.Errorf("font role %q: expected sans, display, label or mono", role)
	}
	return fmt.Sprintf("%q, %s", family, fallback), nil
}

// renderCSS writes the palette as the browser wants it: values exactly as
// authored, translucency included, plus the @theme block that turns each role
// into a Tailwind utility.
//
// Nothing is flattened here. The page composites rgba() against whatever is
// behind it, which is the effect the design asks for; resolving it in advance
// would replace a translucent overlay with a fixed shade that is only correct
// on one background.
func renderCSS(d doc) (string, error) {
	var b strings.Builder
	b.WriteString("/* Code generated by gentokens. DO NOT EDIT. */\n")
	b.WriteString("/* Source: design/tokens.json — edit there, then `go generate ./...` */\n\n")

	for _, block := range []struct {
		selector string
		pick     func(pair) string
	}{
		{":root", func(p pair) string { return p.Light }},
		{".dark", func(p pair) string { return p.Dark }},
	} {
		fmt.Fprintf(&b, "%s {\n", block.selector)
		for _, name := range roles(d.Colors) {
			fmt.Fprintf(&b, "  --%s: %s;\n", name, block.pick(d.Colors[name]))
		}
		for _, name := range roles(d.Effects) {
			fmt.Fprintf(&b, "  --%s: %s;\n", name, block.pick(d.Effects[name]))
		}
		b.WriteString("}\n\n")
	}

	// @theme inline, not @theme: the utilities have to resolve through the
	// custom properties above so switching .dark repaints without rebuilding.
	b.WriteString("@theme inline {\n")
	for _, name := range roles(d.Colors) {
		fmt.Fprintf(&b, "  --color-%s: var(--%s);\n", name, name)
	}
	for _, role := range slices.Sorted(maps.Keys(d.Fonts)) {
		stack, err := fontStack(role, d.Fonts[role])
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "  --font-%s: %s;\n", role, stack)
	}
	b.WriteString("}\n")
	return b.String(), nil
}

// renderGo writes the palette as the terminal wants it: one solid colour per
// role, per theme, resolved at generation time.
func renderGo(d doc) (string, error) {
	names := roles(d.Colors)

	var b strings.Builder
	b.WriteString("// Code generated by gentokens. DO NOT EDIT.\n")
	b.WriteString("// Source: design/tokens.json — edit there, then `go generate ./...`\n\n")
	b.WriteString("package theme\n\n")
	b.WriteString("// Palette is one theme's colours, already resolved to solid values.\n")
	b.WriteString("// Roles that the stylesheet keeps translucent are composited against that\n")
	b.WriteString("// theme's background here, because a terminal cell holds one colour.\n")
	b.WriteString("type Palette struct {\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%s string\n", fieldName(name))
	}
	b.WriteString("}\n\n")

	for _, v := range []struct {
		varName string
		pick    func(pair) string
	}{
		{"Light", func(p pair) string { return p.Light }},
		{"Dark", func(p pair) string { return p.Dark }},
	} {
		backdrop := v.pick(d.Colors[bgRole])
		fmt.Fprintf(&b, "// %s is the %s theme.\nvar %s = Palette{\n", v.varName, strings.ToLower(v.varName), v.varName)
		for _, name := range names {
			solid, err := theme.Flatten(v.pick(d.Colors[name]), backdrop)
			if err != nil {
				return "", fmt.Errorf("role %q in the %s theme: %w", name, strings.ToLower(v.varName), err)
			}
			fmt.Fprintf(&b, "\t%s: %q,\n", fieldName(name), solid)
		}
		b.WriteString("}\n\n")
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("format generated source: %w", err)
	}
	return string(out), nil
}

// fieldName turns a CSS role into a Go field: on-surface-variant becomes
// OnSurfaceVariant, kpi-1-bg becomes Kpi1Bg.
func fieldName(role string) string {
	var b strings.Builder
	for part := range strings.SplitSeq(role, "-") {
		if part == "" {
			continue
		}
		r := []rune(part)
		b.WriteRune(unicode.ToUpper(r[0]))
		b.WriteString(string(r[1:]))
	}
	return b.String()
}
